/* A recursive-descent parser generated by peg 0.1.2 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 54

//#define YYSTYPE Node *
#include <cstdio>
#include <iostream>

//#define YY_DEBUG
#define YYSTYPE string

//#include "visitor.h"

//int yylex (void);
//void yyerror (char const *);

using namespace std;

int source_line = 0;

#ifdef __cplusplus 
#define __MALLOC(type,num) (new type[(num)])
#else
#define __MALLOC(type,num) (type *)malloc(sizeof(type)*(num))
#endif
#ifndef YY_VARIABLE
#define YY_VARIABLE(T)	static T
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yybegin= yypos, 1)
#endif
#ifndef YY_END
#define YY_END		( yyend= yypos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif

#ifndef YY_PART

typedef void (*yyaction)(char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

YY_VARIABLE(char *   ) yybuf= 0;
YY_VARIABLE(int	     ) yybuflen= 0;
YY_VARIABLE(int	     ) yypos= 0;
YY_VARIABLE(int	     ) yylimit= 0;
YY_VARIABLE(char *   ) yytext= 0;
YY_VARIABLE(int	     ) yytextlen= 0;
YY_VARIABLE(int	     ) yybegin= 0;
YY_VARIABLE(int	     ) yyend= 0;
YY_VARIABLE(int	     ) yytextmax= 0;
YY_VARIABLE(yythunk *) yythunks= 0;
YY_VARIABLE(int	     ) yythunkslen= 0;
YY_VARIABLE(int      ) yythunkpos= 0;
YY_VARIABLE(YYSTYPE  ) yy;
YY_VARIABLE(YYSTYPE *) yyval= 0;
YY_VARIABLE(YYSTYPE *) yyvals= 0;
YY_VARIABLE(int      ) yyvalslen= 0;

YY_LOCAL(int) yyrefill(void)
{
  int yyn;
  while (yybuflen - yypos < 512)
    {
      yybuflen *= 2;
      yybuf= (char*)realloc(yybuf, yybuflen);
    }
  YY_INPUT((yybuf + yypos), yyn, (yybuflen - yypos));
  if (!yyn) return 0;
  yylimit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(void)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  ++yypos;
  return 1;
}

YY_LOCAL(int) yymatchChar(int c)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  if (yybuf[yypos] == c)
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchChar(%c) @ %s\n", c, yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(%c) @ %s\n", c, yybuf+yypos));
  return 0;
}

YY_LOCAL(int) yymatchString(char *s)
{
  int yysav= yypos;
  while (*s)
    {
      if (yypos >= yylimit && !yyrefill()) return 0;
      if (yybuf[yypos] != *s)
        {
          yypos= yysav;
          return 0;
        }
      ++s;
      ++yypos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(unsigned char *bits)
{
  int c;
  if (yypos >= yylimit && !yyrefill()) return 0;
  c= yybuf[yypos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yybuf+yypos));
  return 0;
}

YY_LOCAL(void) yyDo(yyaction action, int begin, int end)
{
  while (yythunkpos >= yythunkslen)
    {
      yythunkslen *= 2;
      yythunks= (yythunk*)realloc(yythunks, sizeof(yythunk) * yythunkslen);
    }
  yythunks[yythunkpos].begin=  begin;
  yythunks[yythunkpos].end=    end;
  yythunks[yythunkpos].action= action;
  ++yythunkpos;
}

YY_LOCAL(int) yyText(int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yytextlen < (yyleng - 1))
	{
	  yytextlen *= 2;
	  yytext= (char*)realloc(yytext, yytextlen);
	}
      memcpy(yytext, yybuf + begin, yyleng);
    }
  yytext[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(void)
{
  int pos;
  for (pos= 0;  pos < yythunkpos;  ++pos)
    {
      yythunk *thunk= &yythunks[pos];
      int yyleng= thunk->end ? yyText(thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yytext));
      thunk->action(yytext, yyleng);
    }
  yythunkpos= 0;
}

YY_LOCAL(void) yyCommit()
{
  if ((yylimit -= yypos))
    {
      memmove(yybuf, yybuf + yypos, yylimit);
    }
  yybegin -= yypos;
  yyend -= yypos;
  yypos= yythunkpos= 0;
}

YY_LOCAL(int) yyAccept(int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone();
      yyCommit();
    }
  return 1;
}

YY_LOCAL(void) yyPush(char *text, int count)	{ yyval += count; }
YY_LOCAL(void) yyPop(char *text, int count)	{ yyval -= count; }
YY_LOCAL(void) yySet(char *text, int count)	{ yyval[count]= yy; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yythunkpos0)

YY_RULE(int) yy_nl(); /* 54 */
YY_RULE(int) yy_num_literal(); /* 53 */
YY_RULE(int) yy_string_literal(); /* 52 */
YY_RULE(int) yy_op_dot(); /* 51 */
YY_RULE(int) yy_term2(); /* 50 */
YY_RULE(int) yy_fcall(); /* 49 */
YY_RULE(int) yy_op_mod(); /* 48 */
YY_RULE(int) yy_op_div(); /* 47 */
YY_RULE(int) yy_op_mul(); /* 46 */
YY_RULE(int) yy_term(); /* 45 */
YY_RULE(int) yy_op_sub(); /* 44 */
YY_RULE(int) yy_op_add(); /* 43 */
YY_RULE(int) yy_product(); /* 42 */
YY_RULE(int) yy_tuple_exp(); /* 41 */
YY_RULE(int) yy_func_call(); /* 40 */
YY_RULE(int) yy_bin_op(); /* 39 */
YY_RULE(int) yy_assign(); /* 38 */
YY_RULE(int) yy_expression(); /* 37 */
YY_RULE(int) yy_statement(); /* 36 */
YY_RULE(int) yy_sline(); /* 35 */
YY_RULE(int) yy_statements(); /* 34 */
YY_RULE(int) yy_multi_stmnt(); /* 33 */
YY_RULE(int) yy_line_stmnt(); /* 32 */
YY_RULE(int) yy_block(); /* 31 */
YY_RULE(int) yy_code_lit(); /* 30 */
YY_RULE(int) yy_all_literal(); /* 29 */
YY_RULE(int) yy_def_name(); /* 28 */
YY_RULE(int) yy_definition(); /* 27 */
YY_RULE(int) yy_type_tuple(); /* 26 */
YY_RULE(int) yy_type(); /* 25 */
YY_RULE(int) yy_sum(); /* 24 */
YY_RULE(int) yy_op_assign(); /* 23 */
YY_RULE(int) yy_init(); /* 22 */
YY_RULE(int) yy_var(); /* 21 */
YY_RULE(int) yy_var_list(); /* 20 */
YY_RULE(int) yy_type_exp(); /* 19 */
YY_RULE(int) yy_decl_single(); /* 18 */
YY_RULE(int) yy_op_comma(); /* 17 */
YY_RULE(int) yy_name(); /* 16 */
YY_RULE(int) yy_literal(); /* 15 */
YY_RULE(int) yy_const_exp(); /* 14 */
YY_RULE(int) yy_op_define(); /* 13 */
YY_RULE(int) yy_name_list(); /* 12 */
YY_RULE(int) yy_auto_decl(); /* 11 */
YY_RULE(int) yy_declaration(); /* 10 */
YY_RULE(int) yy___(); /* 9 */
YY_RULE(int) yy_define(); /* 8 */
YY_RULE(int) yy_declare(); /* 7 */
YY_RULE(int) yy_nll(); /* 6 */
YY_RULE(int) yy_decl(); /* 5 */
YY_RULE(int) yy_EOF(); /* 4 */
YY_RULE(int) yy__(); /* 3 */
YY_RULE(int) yy_decls(); /* 2 */
YY_RULE(int) yy_program(); /* 1 */

YY_ACTION(void) yy_1_nl(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_nl\n"));
  ++source_line;;
}
YY_ACTION(void) yy_1_num_literal(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_num_literal\n"));
  yy = yytext;;
}
YY_ACTION(void) yy_1_string_literal(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_string_literal\n"));
  yy = yytext;;
}
YY_ACTION(void) yy_4_literal(char *yytext, int yyleng)
{
#define c2 yyval[-1]
#define c1 yyval[-2]
#define d yyval[-3]
#define n yyval[-4]
#define s yyval[-5]
  yyprintf((stderr, "do yy_4_literal\n"));
  yy = c2;;
#undef c2
#undef c1
#undef d
#undef n
#undef s
}
YY_ACTION(void) yy_3_literal(char *yytext, int yyleng)
{
#define c2 yyval[-1]
#define c1 yyval[-2]
#define d yyval[-3]
#define n yyval[-4]
#define s yyval[-5]
  yyprintf((stderr, "do yy_3_literal\n"));
  yy = d + " : " + c1;;
#undef c2
#undef c1
#undef d
#undef n
#undef s
}
YY_ACTION(void) yy_2_literal(char *yytext, int yyleng)
{
#define c2 yyval[-1]
#define c1 yyval[-2]
#define d yyval[-3]
#define n yyval[-4]
#define s yyval[-5]
  yyprintf((stderr, "do yy_2_literal\n"));
  yy = n;;
#undef c2
#undef c1
#undef d
#undef n
#undef s
}
YY_ACTION(void) yy_1_literal(char *yytext, int yyleng)
{
#define c2 yyval[-1]
#define c1 yyval[-2]
#define d yyval[-3]
#define n yyval[-4]
#define s yyval[-5]
  yyprintf((stderr, "do yy_1_literal\n"));
  yy = s;;
#undef c2
#undef c1
#undef d
#undef n
#undef s
}
YY_ACTION(void) yy_1_name(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_name\n"));
  yy = string("<") + yytext + ">";;
}
YY_ACTION(void) yy_1_fcall(char *yytext, int yyleng)
{
#define t2 yyval[-1]
#define t1 yyval[-2]
  yyprintf((stderr, "do yy_1_fcall\n"));
  yy = "fn: " + t1 + "(" + t2 + ")";;
#undef t2
#undef t1
}
YY_ACTION(void) yy_4_term2(char *yytext, int yyleng)
{
#define n yyval[-1]
#define l yyval[-2]
#define n2 yyval[-3]
#define n1 yyval[-4]
#define s yyval[-5]
  yyprintf((stderr, "do yy_4_term2\n"));
  yy = "n:" + n;;
#undef n
#undef l
#undef n2
#undef n1
#undef s
}
YY_ACTION(void) yy_3_term2(char *yytext, int yyleng)
{
#define n yyval[-1]
#define l yyval[-2]
#define n2 yyval[-3]
#define n1 yyval[-4]
#define s yyval[-5]
  yyprintf((stderr, "do yy_3_term2\n"));
  yy = "l:(" + l +")";;
#undef n
#undef l
#undef n2
#undef n1
#undef s
}
YY_ACTION(void) yy_2_term2(char *yytext, int yyleng)
{
#define n yyval[-1]
#define l yyval[-2]
#define n2 yyval[-3]
#define n1 yyval[-4]
#define s yyval[-5]
  yyprintf((stderr, "do yy_2_term2\n"));
  yy = ".:" + n1 + "." + n2;;
#undef n
#undef l
#undef n2
#undef n1
#undef s
}
YY_ACTION(void) yy_1_term2(char *yytext, int yyleng)
{
#define n yyval[-1]
#define l yyval[-2]
#define n2 yyval[-3]
#define n1 yyval[-4]
#define s yyval[-5]
  yyprintf((stderr, "do yy_1_term2\n"));
  yy = "(" + s + ")";;
#undef n
#undef l
#undef n2
#undef n1
#undef s
}
YY_ACTION(void) yy_3_term(char *yytext, int yyleng)
{
#define t2 yyval[-1]
#define t1 yyval[-2]
#define f yyval[-3]
  yyprintf((stderr, "do yy_3_term\n"));
  yy = t2;;
#undef t2
#undef t1
#undef f
}
YY_ACTION(void) yy_2_term(char *yytext, int yyleng)
{
#define t2 yyval[-1]
#define t1 yyval[-2]
#define f yyval[-3]
  yyprintf((stderr, "do yy_2_term\n"));
  yy = t1;;
#undef t2
#undef t1
#undef f
}
YY_ACTION(void) yy_1_term(char *yytext, int yyleng)
{
#define t2 yyval[-1]
#define t1 yyval[-2]
#define f yyval[-3]
  yyprintf((stderr, "do yy_1_term\n"));
  yy = f;;
#undef t2
#undef t1
#undef f
}
YY_ACTION(void) yy_2_product(char *yytext, int yyleng)
{
#define t2 yyval[-1]
#define t1 yyval[-2]
  yyprintf((stderr, "do yy_2_product\n"));
  yy = "*: (" + t1 + ")";;
#undef t2
#undef t1
}
YY_ACTION(void) yy_1_product(char *yytext, int yyleng)
{
#define t2 yyval[-1]
#define t1 yyval[-2]
  yyprintf((stderr, "do yy_1_product\n"));
  t1 += " * " + t2;;
#undef t2
#undef t1
}
YY_ACTION(void) yy_2_sum(char *yytext, int yyleng)
{
#define p2 yyval[-1]
#define p1 yyval[-2]
  yyprintf((stderr, "do yy_2_sum\n"));
  yy = "+: (" + p1 + ")";;
#undef p2
#undef p1
}
YY_ACTION(void) yy_1_sum(char *yytext, int yyleng)
{
#define p2 yyval[-1]
#define p1 yyval[-2]
  yyprintf((stderr, "do yy_1_sum\n"));
  p1 += " + " + p2;;
#undef p2
#undef p1
}
YY_ACTION(void) yy_2_tuple_exp(char *yytext, int yyleng)
{
#define s2 yyval[-1]
#define s1 yyval[-2]
  yyprintf((stderr, "do yy_2_tuple_exp\n"));
  yy = "tup: (" + s1 + ")";
#undef s2
#undef s1
}
YY_ACTION(void) yy_1_tuple_exp(char *yytext, int yyleng)
{
#define s2 yyval[-1]
#define s1 yyval[-2]
  yyprintf((stderr, "do yy_1_tuple_exp\n"));
  s1 += "," + s2;;
#undef s2
#undef s1
}
YY_ACTION(void) yy_2_func_call(char *yytext, int yyleng)
{
#define s2 yyval[-1]
#define s1 yyval[-2]
#define n yyval[-3]
  yyprintf((stderr, "do yy_2_func_call\n"));
  yy = "f: " + n + " (" + s1 + ")";;
#undef s2
#undef s1
#undef n
}
YY_ACTION(void) yy_1_func_call(char *yytext, int yyleng)
{
#define s2 yyval[-1]
#define s1 yyval[-2]
#define n yyval[-3]
  yyprintf((stderr, "do yy_1_func_call\n"));
  s1 += ", " + s2;;
#undef s2
#undef s1
#undef n
}
YY_ACTION(void) yy_2_expression(char *yytext, int yyleng)
{
#define t yyval[-1]
#define f yyval[-2]
  yyprintf((stderr, "do yy_2_expression\n"));
  yy = t;;
#undef t
#undef f
}
YY_ACTION(void) yy_1_expression(char *yytext, int yyleng)
{
#define t yyval[-1]
#define f yyval[-2]
  yyprintf((stderr, "do yy_1_expression\n"));
  yy = f;;
#undef t
#undef f
}
YY_ACTION(void) yy_1_assign(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_assign\n"));
  yy = "ass";;
}
YY_ACTION(void) yy_2_statement(char *yytext, int yyleng)
{
#define e2 yyval[-1]
#define e1 yyval[-2]
  yyprintf((stderr, "do yy_2_statement\n"));
  yy = "ex: " + e1;;
#undef e2
#undef e1
}
YY_ACTION(void) yy_1_statement(char *yytext, int yyleng)
{
#define e2 yyval[-1]
#define e1 yyval[-2]
  yyprintf((stderr, "do yy_1_statement\n"));
  e1 += " = " + e2;;
#undef e2
#undef e1
}
YY_ACTION(void) yy_2_statements(char *yytext, int yyleng)
{
#define s2 yyval[-1]
#define s1 yyval[-2]
  yyprintf((stderr, "do yy_2_statements\n"));
  yy = "s: " + s1;;
#undef s2
#undef s1
}
YY_ACTION(void) yy_1_statements(char *yytext, int yyleng)
{
#define s2 yyval[-1]
#define s1 yyval[-2]
  yyprintf((stderr, "do yy_1_statements\n"));
  s1 += "; " + s2;;
#undef s2
#undef s1
}
YY_ACTION(void) yy_5_sline(char *yytext, int yyleng)
{
#define s yyval[-1]
#define d2 yyval[-2]
#define d1 yyval[-3]
  yyprintf((stderr, "do yy_5_sline\n"));
  printf("syntax error2 in line %d:\n>\t%s\n", source_line, yytext); yy = "error";;
#undef s
#undef d2
#undef d1
}
YY_ACTION(void) yy_4_sline(char *yytext, int yyleng)
{
#define s yyval[-1]
#define d2 yyval[-2]
#define d1 yyval[-3]
  yyprintf((stderr, "do yy_4_sline\n"));
  yy = "";;
#undef s
#undef d2
#undef d1
}
YY_ACTION(void) yy_3_sline(char *yytext, int yyleng)
{
#define s yyval[-1]
#define d2 yyval[-2]
#define d1 yyval[-3]
  yyprintf((stderr, "do yy_3_sline\n"));
  yy = s;;
#undef s
#undef d2
#undef d1
}
YY_ACTION(void) yy_2_sline(char *yytext, int yyleng)
{
#define s yyval[-1]
#define d2 yyval[-2]
#define d1 yyval[-3]
  yyprintf((stderr, "do yy_2_sline\n"));
  yy = d2;;
#undef s
#undef d2
#undef d1
}
YY_ACTION(void) yy_1_sline(char *yytext, int yyleng)
{
#define s yyval[-1]
#define d2 yyval[-2]
#define d1 yyval[-3]
  yyprintf((stderr, "do yy_1_sline\n"));
  yy = d1;;
#undef s
#undef d2
#undef d1
}
YY_ACTION(void) yy_2_multi_stmnt(char *yytext, int yyleng)
{
#define s2 yyval[-1]
#define s1 yyval[-2]
  yyprintf((stderr, "do yy_2_multi_stmnt\n"));
  yy = "\n\t{sl: " + s1 + "\n\t}\n";;
#undef s2
#undef s1
}
YY_ACTION(void) yy_1_multi_stmnt(char *yytext, int yyleng)
{
#define s2 yyval[-1]
#define s1 yyval[-2]
  yyprintf((stderr, "do yy_1_multi_stmnt\n"));
  s1 += "\nsl: " + s2;;
#undef s2
#undef s1
}
YY_ACTION(void) yy_1_line_stmnt(char *yytext, int yyleng)
{
#define s yyval[-1]
  yyprintf((stderr, "do yy_1_line_stmnt\n"));
  yy = "{sts: " + s + "}";;
#undef s
}
YY_ACTION(void) yy_2_block(char *yytext, int yyleng)
{
#define m yyval[-1]
#define l yyval[-2]
  yyprintf((stderr, "do yy_2_block\n"));
  yy = m;;
#undef m
#undef l
}
YY_ACTION(void) yy_1_block(char *yytext, int yyleng)
{
#define m yyval[-1]
#define l yyval[-2]
  yyprintf((stderr, "do yy_1_block\n"));
  yy = l;;
#undef m
#undef l
}
YY_ACTION(void) yy_2_code_lit(char *yytext, int yyleng)
{
#define b2 yyval[-1]
#define b yyval[-2]
#define d yyval[-3]
  yyprintf((stderr, "do yy_2_code_lit\n"));
  yy = "vl2: " + b2;;
#undef b2
#undef b
#undef d
}
YY_ACTION(void) yy_1_code_lit(char *yytext, int yyleng)
{
#define b2 yyval[-1]
#define b yyval[-2]
#define d yyval[-3]
  yyprintf((stderr, "do yy_1_code_lit\n"));
  yy = "vl: " + d + " -> " + b;;
#undef b2
#undef b
#undef d
}
YY_ACTION(void) yy_3_all_literal(char *yytext, int yyleng)
{
#define l1 yyval[-1]
#define l2 yyval[-2]
  yyprintf((stderr, "do yy_3_all_literal\n"));
  printf("syntax error in line %d:\n>\t%s\n", source_line, yytext); yy = "error";;
#undef l1
#undef l2
}
YY_ACTION(void) yy_2_all_literal(char *yytext, int yyleng)
{
#define l1 yyval[-1]
#define l2 yyval[-2]
  yyprintf((stderr, "do yy_2_all_literal\n"));
  yy = "lit";;
#undef l1
#undef l2
}
YY_ACTION(void) yy_1_all_literal(char *yytext, int yyleng)
{
#define l1 yyval[-1]
#define l2 yyval[-2]
  yyprintf((stderr, "do yy_1_all_literal\n"));
  yy = "cl: " + l2;;
#undef l1
#undef l2
}
YY_ACTION(void) yy_2_def_name(char *yytext, int yyleng)
{
#define n2 yyval[-1]
#define n1 yyval[-2]
#define t yyval[-3]
  yyprintf((stderr, "do yy_2_def_name\n"));
  yy = n2;;
#undef n2
#undef n1
#undef t
}
YY_ACTION(void) yy_1_def_name(char *yytext, int yyleng)
{
#define n2 yyval[-1]
#define n1 yyval[-2]
#define t yyval[-3]
  yyprintf((stderr, "do yy_1_def_name\n"));
  yy = "t: " + t + " v: " + n1;;
#undef n2
#undef n1
#undef t
}
YY_ACTION(void) yy_1_definition(char *yytext, int yyleng)
{
#define l yyval[-1]
#define n yyval[-2]
  yyprintf((stderr, "do yy_1_definition\n"));
  yy = n + " := " + l;;
#undef l
#undef n
}
YY_ACTION(void) yy_1_define(char *yytext, int yyleng)
{
#define d yyval[-1]
  yyprintf((stderr, "do yy_1_define\n"));
  yy = "def: " + d;;
#undef d
}
YY_ACTION(void) yy_1_type(char *yytext, int yyleng)
{
#define n yyval[-1]
  yyprintf((stderr, "do yy_1_type\n"));
  yy = n;;
#undef n
}
YY_ACTION(void) yy_2_type_tuple(char *yytext, int yyleng)
{
#define t2 yyval[-1]
#define t yyval[-2]
  yyprintf((stderr, "do yy_2_type_tuple\n"));
  yy = t;;
#undef t2
#undef t
}
YY_ACTION(void) yy_1_type_tuple(char *yytext, int yyleng)
{
#define t2 yyval[-1]
#define t yyval[-2]
  yyprintf((stderr, "do yy_1_type_tuple\n"));
  t += ',' + t2;;
#undef t2
#undef t
}
YY_ACTION(void) yy_2_type_exp(char *yytext, int yyleng)
{
#define tt yyval[-1]
#define t yyval[-2]
  yyprintf((stderr, "do yy_2_type_exp\n"));
  yy = tt;;
#undef tt
#undef t
}
YY_ACTION(void) yy_1_type_exp(char *yytext, int yyleng)
{
#define tt yyval[-1]
#define t yyval[-2]
  yyprintf((stderr, "do yy_1_type_exp\n"));
  yy = t;;
#undef tt
#undef t
}
YY_ACTION(void) yy_1_init(char *yytext, int yyleng)
{
#define s yyval[-1]
  yyprintf((stderr, "do yy_1_init\n"));
  yy = s;;
#undef s
}
YY_ACTION(void) yy_2_var(char *yytext, int yyleng)
{
#define i yyval[-1]
#define n yyval[-2]
  yyprintf((stderr, "do yy_2_var\n"));
  yy = n;;
#undef i
#undef n
}
YY_ACTION(void) yy_1_var(char *yytext, int yyleng)
{
#define i yyval[-1]
#define n yyval[-2]
  yyprintf((stderr, "do yy_1_var\n"));
  n += ":=" + i;;
#undef i
#undef n
}
YY_ACTION(void) yy_2_var_list(char *yytext, int yyleng)
{
#define v2 yyval[-1]
#define v1 yyval[-2]
  yyprintf((stderr, "do yy_2_var_list\n"));
  yy = "vl: (" + v1 + ")";;
#undef v2
#undef v1
}
YY_ACTION(void) yy_1_var_list(char *yytext, int yyleng)
{
#define v2 yyval[-1]
#define v1 yyval[-2]
  yyprintf((stderr, "do yy_1_var_list\n"));
  v1 += "," + v2;;
#undef v2
#undef v1
}
YY_ACTION(void) yy_1_decl_single(char *yytext, int yyleng)
{
#define v yyval[-1]
#define t yyval[-2]
  yyprintf((stderr, "do yy_1_decl_single\n"));
  yy = "t: " + t + "v: " + v;;
#undef v
#undef t
}
YY_ACTION(void) yy_2_declaration(char *yytext, int yyleng)
{
#define d2 yyval[-1]
#define d yyval[-2]
  yyprintf((stderr, "do yy_2_declaration\n"));
  yy = d;;
#undef d2
#undef d
}
YY_ACTION(void) yy_1_declaration(char *yytext, int yyleng)
{
#define d2 yyval[-1]
#define d yyval[-2]
  yyprintf((stderr, "do yy_1_declaration\n"));
  d += ",," + d2;;
#undef d2
#undef d
}
YY_ACTION(void) yy_2_name_list(char *yytext, int yyleng)
{
#define n2 yyval[-1]
#define n1 yyval[-2]
  yyprintf((stderr, "do yy_2_name_list\n"));
  yy = n1;;
#undef n2
#undef n1
}
YY_ACTION(void) yy_1_name_list(char *yytext, int yyleng)
{
#define n2 yyval[-1]
#define n1 yyval[-2]
  yyprintf((stderr, "do yy_1_name_list\n"));
  n1 += "," + n2;;
#undef n2
#undef n1
}
YY_ACTION(void) yy_1_const_exp(char *yytext, int yyleng)
{
#define l yyval[-1]
  yyprintf((stderr, "do yy_1_const_exp\n"));
  yy = l;;
#undef l
}
YY_ACTION(void) yy_1_auto_decl(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_auto_decl\n"));
  yy = "auto";;
}
YY_ACTION(void) yy_2_declare(char *yytext, int yyleng)
{
#define d yyval[-1]
  yyprintf((stderr, "do yy_2_declare\n"));
  yy = "auto";;
#undef d
}
YY_ACTION(void) yy_1_declare(char *yytext, int yyleng)
{
#define d yyval[-1]
  yyprintf((stderr, "do yy_1_declare\n"));
  yy = "var (" + d + ")";;
#undef d
}
YY_ACTION(void) yy_5_decl(char *yytext, int yyleng)
{
#define e yyval[-1]
#define c yyval[-2]
  yyprintf((stderr, "do yy_5_decl\n"));
  printf("syntax error on line %d:\n>\t%s\n", source_line, yytext); yy = "error";;
#undef e
#undef c
}
YY_ACTION(void) yy_4_decl(char *yytext, int yyleng)
{
#define e yyval[-1]
#define c yyval[-2]
  yyprintf((stderr, "do yy_4_decl\n"));
  yy = "";;
#undef e
#undef c
}
YY_ACTION(void) yy_3_decl(char *yytext, int yyleng)
{
#define e yyval[-1]
#define c yyval[-2]
  yyprintf((stderr, "do yy_3_decl\n"));
  yy = "//";;
#undef e
#undef c
}
YY_ACTION(void) yy_2_decl(char *yytext, int yyleng)
{
#define e yyval[-1]
#define c yyval[-2]
  yyprintf((stderr, "do yy_2_decl\n"));
  yy = e;;
#undef e
#undef c
}
YY_ACTION(void) yy_1_decl(char *yytext, int yyleng)
{
#define e yyval[-1]
#define c yyval[-2]
  yyprintf((stderr, "do yy_1_decl\n"));
  yy = c;;
#undef e
#undef c
}
YY_ACTION(void) yy_2_decls(char *yytext, int yyleng)
{
#define d2 yyval[-1]
#define d1 yyval[-2]
  yyprintf((stderr, "do yy_2_decls\n"));
  printf("decls: %s\n", d1.c_str()); yy = "d: " + d1; ;
#undef d2
#undef d1
}
YY_ACTION(void) yy_1_decls(char *yytext, int yyleng)
{
#define d2 yyval[-1]
#define d1 yyval[-2]
  yyprintf((stderr, "do yy_1_decls\n"));
  d1 += "\nd: " + d2;;
#undef d2
#undef d1
}
YY_ACTION(void) yy_1_program(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_program\n"));
  printf("done on line %d\n", source_line); yy = "";;
}

YY_RULE(int) yy_nl()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "nl"));  if (!yymatchChar('\n')) goto l1;  yyDo(yy_1_nl, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "nl", yybuf+yypos));
  return 1;
  l1:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "nl", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_num_literal()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "num_literal"));
  {  int yypos3= yypos, yythunkpos3= yythunkpos;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l4;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l4;
  l5:;	
  {  int yypos6= yypos, yythunkpos6= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l6;  goto l5;
  l6:;	  yypos= yypos6; yythunkpos= yythunkpos6;
  }  goto l3;
  l4:;	  yypos= yypos3; yythunkpos= yythunkpos3;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l2;
  l7:;	
  {  int yypos8= yypos, yythunkpos8= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l8;  goto l7;
  l8:;	  yypos= yypos8; yythunkpos= yythunkpos8;
  }
  {  int yypos9= yypos, yythunkpos9= yythunkpos;  if (!yymatchChar('.')) goto l9;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l9;
  l11:;	
  {  int yypos12= yypos, yythunkpos12= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l12;  goto l11;
  l12:;	  yypos= yypos12; yythunkpos= yythunkpos12;
  }  goto l10;
  l9:;	  yypos= yypos9; yythunkpos= yythunkpos9;
  }
  l10:;	  yyText(yybegin, yyend);  if (!(YY_END)) goto l2;  yyDo(yy_1_num_literal, yybegin, yyend);
  }
  l3:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "num_literal", yybuf+yypos));
  return 1;
  l2:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "num_literal", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_string_literal()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "string_literal"));  if (!yymatchChar('"')) goto l13;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l13;
  l14:;	
  {  int yypos15= yypos, yythunkpos15= yythunkpos;  if (!yymatchClass((unsigned char *)"\377\377\377\377\373\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l15;  goto l14;
  l15:;	  yypos= yypos15; yythunkpos= yythunkpos15;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l13;  if (!yymatchChar('"')) goto l13;  yyDo(yy_1_string_literal, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "string_literal", yybuf+yypos));
  return 1;
  l13:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "string_literal", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_op_dot()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "op_dot"));  if (!yymatchChar('.')) goto l16;  if (!yy___()) goto l16;
  yyprintf((stderr, "  ok   %s @ %s\n", "op_dot", yybuf+yypos));
  return 1;
  l16:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "op_dot", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_term2()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 5, 0);
  yyprintf((stderr, "%s\n", "term2"));
  {  int yypos18= yypos, yythunkpos18= yythunkpos;  if (!yymatchChar('(')) goto l19;  if (!yy___()) goto l19;  if (!yy_statement()) goto l19;  yyDo(yySet, -5, 0);  if (!yymatchChar(')')) goto l19;  if (!yy__()) goto l19;  yyDo(yy_1_term2, yybegin, yyend);  goto l18;
  l19:;	  yypos= yypos18; yythunkpos= yythunkpos18;  if (!yy_name()) goto l20;  yyDo(yySet, -4, 0);  if (!yy__()) goto l20;  if (!yy_op_dot()) goto l20;  if (!yy_name()) goto l20;  yyDo(yySet, -3, 0);  if (!yy__()) goto l20;  yyDo(yy_2_term2, yybegin, yyend);  goto l18;
  l20:;	  yypos= yypos18; yythunkpos= yythunkpos18;  if (!yy_literal()) goto l21;  yyDo(yySet, -2, 0);  if (!yy__()) goto l21;  yyDo(yy_3_term2, yybegin, yyend);  goto l18;
  l21:;	  yypos= yypos18; yythunkpos= yythunkpos18;  if (!yy_name()) goto l17;  yyDo(yySet, -1, 0);  if (!yy__()) goto l17;  yyDo(yy_4_term2, yybegin, yyend);
  }
  l18:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "term2", yybuf+yypos));  yyDo(yyPop, 5, 0);
  return 1;
  l17:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "term2", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_fcall()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "fcall"));  if (!yy_term2()) goto l22;  yyDo(yySet, -2, 0);  if (!yy_term()) goto l22;  yyDo(yySet, -1, 0);  yyDo(yy_1_fcall, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "fcall", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l22:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "fcall", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_op_mod()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "op_mod"));  if (!yymatchChar('%')) goto l23;  if (!yy___()) goto l23;
  yyprintf((stderr, "  ok   %s @ %s\n", "op_mod", yybuf+yypos));
  return 1;
  l23:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "op_mod", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_op_div()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "op_div"));  if (!yymatchChar('/')) goto l24;  if (!yy___()) goto l24;
  yyprintf((stderr, "  ok   %s @ %s\n", "op_div", yybuf+yypos));
  return 1;
  l24:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "op_div", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_op_mul()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "op_mul"));  if (!yymatchChar('*')) goto l25;  if (!yy___()) goto l25;
  yyprintf((stderr, "  ok   %s @ %s\n", "op_mul", yybuf+yypos));
  return 1;
  l25:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "op_mul", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_term()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "term"));
  {  int yypos27= yypos, yythunkpos27= yythunkpos;  if (!yy_fcall()) goto l28;  yyDo(yySet, -3, 0);  yyDo(yy_1_term, yybegin, yyend);  goto l27;
  l28:;	  yypos= yypos27; yythunkpos= yythunkpos27;  if (!yy_term2()) goto l29;  yyDo(yySet, -2, 0);  yyDo(yy_2_term, yybegin, yyend);  goto l27;
  l29:;	  yypos= yypos27; yythunkpos= yythunkpos27;
  {  int yypos30= yypos, yythunkpos30= yythunkpos;  if (!yymatchString("--")) goto l31;  goto l30;
  l31:;	  yypos= yypos30; yythunkpos= yythunkpos30;  if (!yymatchString("++")) goto l26;
  }
  l30:;	  if (!yy__()) goto l26;  if (!yy_term()) goto l26;  yyDo(yySet, -1, 0);  yyDo(yy_3_term, yybegin, yyend);
  }
  l27:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "term", yybuf+yypos));  yyDo(yyPop, 3, 0);
  return 1;
  l26:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "term", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_op_sub()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "op_sub"));  if (!yymatchChar('-')) goto l32;  if (!yy___()) goto l32;
  yyprintf((stderr, "  ok   %s @ %s\n", "op_sub", yybuf+yypos));
  return 1;
  l32:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "op_sub", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_op_add()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "op_add"));  if (!yymatchChar('+')) goto l33;  if (!yy___()) goto l33;
  yyprintf((stderr, "  ok   %s @ %s\n", "op_add", yybuf+yypos));
  return 1;
  l33:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "op_add", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_product()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "product"));  if (!yy_term()) goto l34;  yyDo(yySet, -2, 0);
  l35:;	
  {  int yypos36= yypos, yythunkpos36= yythunkpos;
  {  int yypos37= yypos, yythunkpos37= yythunkpos;  if (!yy_op_mul()) goto l38;  goto l37;
  l38:;	  yypos= yypos37; yythunkpos= yythunkpos37;  if (!yy_op_div()) goto l39;  goto l37;
  l39:;	  yypos= yypos37; yythunkpos= yythunkpos37;  if (!yy_op_mod()) goto l36;
  }
  l37:;	  if (!yy_term()) goto l36;  yyDo(yySet, -1, 0);  yyDo(yy_1_product, yybegin, yyend);  goto l35;
  l36:;	  yypos= yypos36; yythunkpos= yythunkpos36;
  }  yyDo(yy_2_product, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "product", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l34:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "product", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_tuple_exp()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "tuple_exp"));  if (!yy_sum()) goto l40;  yyDo(yySet, -2, 0);
  l41:;	
  {  int yypos42= yypos, yythunkpos42= yythunkpos;  if (!yy_op_comma()) goto l42;  if (!yy_sum()) goto l42;  yyDo(yySet, -1, 0);  yyDo(yy_1_tuple_exp, yybegin, yyend);  goto l41;
  l42:;	  yypos= yypos42; yythunkpos= yythunkpos42;
  }  yyDo(yy_2_tuple_exp, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "tuple_exp", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l40:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "tuple_exp", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_func_call()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "func_call"));  if (!yy_name()) goto l43;  yyDo(yySet, -3, 0);  if (!yy__()) goto l43;  if (!yy_sum()) goto l43;  yyDo(yySet, -2, 0);  if (!yy_op_comma()) goto l43;  if (!yy_sum()) goto l43;  yyDo(yySet, -1, 0);  yyDo(yy_1_func_call, yybegin, yyend);
  l44:;	
  {  int yypos45= yypos, yythunkpos45= yythunkpos;  if (!yy_op_comma()) goto l45;  if (!yy_sum()) goto l45;  yyDo(yySet, -1, 0);  yyDo(yy_1_func_call, yybegin, yyend);  goto l44;
  l45:;	  yypos= yypos45; yythunkpos= yythunkpos45;
  }  yyDo(yy_2_func_call, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "func_call", yybuf+yypos));  yyDo(yyPop, 3, 0);
  return 1;
  l43:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "func_call", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_bin_op()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "bin_op"));
  {  int yypos47= yypos, yythunkpos47= yythunkpos;  if (!yymatchChar('+')) goto l48;  goto l47;
  l48:;	  yypos= yypos47; yythunkpos= yythunkpos47;  if (!yymatchChar('-')) goto l49;  goto l47;
  l49:;	  yypos= yypos47; yythunkpos= yythunkpos47;  if (!yymatchChar('/')) goto l50;  goto l47;
  l50:;	  yypos= yypos47; yythunkpos= yythunkpos47;  if (!yymatchChar('*')) goto l51;  goto l47;
  l51:;	  yypos= yypos47; yythunkpos= yythunkpos47;  if (!yymatchChar('%')) goto l46;
  }
  l47:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "bin_op", yybuf+yypos));
  return 1;
  l46:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bin_op", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_assign()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "assign"));
  {  int yypos53= yypos, yythunkpos53= yythunkpos;  if (!yy_bin_op()) goto l53;  goto l54;
  l53:;	  yypos= yypos53; yythunkpos= yythunkpos53;
  }
  l54:;	  if (!yy_op_assign()) goto l52;  yyDo(yy_1_assign, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "assign", yybuf+yypos));
  return 1;
  l52:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "assign", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_expression()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "expression"));
  {  int yypos56= yypos, yythunkpos56= yythunkpos;  if (!yy_func_call()) goto l57;  yyDo(yySet, -2, 0);  yyDo(yy_1_expression, yybegin, yyend);  goto l56;
  l57:;	  yypos= yypos56; yythunkpos= yythunkpos56;  if (!yy_tuple_exp()) goto l55;  yyDo(yySet, -1, 0);  yyDo(yy_2_expression, yybegin, yyend);
  }
  l56:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "expression", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l55:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "expression", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_statement()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "statement"));  if (!yy_expression()) goto l58;  yyDo(yySet, -2, 0);
  l59:;	
  {  int yypos60= yypos, yythunkpos60= yythunkpos;  if (!yy_assign()) goto l60;  if (!yy_expression()) goto l60;  yyDo(yySet, -1, 0);  yyDo(yy_1_statement, yybegin, yyend);  goto l59;
  l60:;	  yypos= yypos60; yythunkpos= yythunkpos60;
  }  yyDo(yy_2_statement, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "statement", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l58:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "statement", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_sline()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "sline"));
  {  int yypos62= yypos, yythunkpos62= yythunkpos;  if (!yy_declare()) goto l63;  yyDo(yySet, -3, 0);  yyDo(yy_1_sline, yybegin, yyend);  goto l62;
  l63:;	  yypos= yypos62; yythunkpos= yythunkpos62;  if (!yy_define()) goto l64;  yyDo(yySet, -2, 0);  yyDo(yy_2_sline, yybegin, yyend);  goto l62;
  l64:;	  yypos= yypos62; yythunkpos= yythunkpos62;  if (!yy_statements()) goto l65;  yyDo(yySet, -1, 0);  yyDo(yy_3_sline, yybegin, yyend);  goto l62;
  l65:;	  yypos= yypos62; yythunkpos= yythunkpos62;  if (!yy__()) goto l66;  yyDo(yy_4_sline, yybegin, yyend);  goto l62;
  l66:;	  yypos= yypos62; yythunkpos= yythunkpos62;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l61;  if (!yymatchClass((unsigned char *)"\377\371\377\377\376\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l61;
  l69:;	
  {  int yypos70= yypos, yythunkpos70= yythunkpos;  if (!yymatchClass((unsigned char *)"\377\371\377\377\376\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l70;  goto l69;
  l70:;	  yypos= yypos70; yythunkpos= yythunkpos70;
  }  if (!yy__()) goto l61;
  l67:;	
  {  int yypos68= yypos, yythunkpos68= yythunkpos;  if (!yymatchClass((unsigned char *)"\377\371\377\377\376\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l68;
  l71:;	
  {  int yypos72= yypos, yythunkpos72= yythunkpos;  if (!yymatchClass((unsigned char *)"\377\371\377\377\376\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l72;  goto l71;
  l72:;	  yypos= yypos72; yythunkpos= yythunkpos72;
  }  if (!yy__()) goto l68;  goto l67;
  l68:;	  yypos= yypos68; yythunkpos= yythunkpos68;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l61;  yyDo(yy_5_sline, yybegin, yyend);
  }
  l62:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "sline", yybuf+yypos));  yyDo(yyPop, 3, 0);
  return 1;
  l61:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "sline", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_statements()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "statements"));  if (!yy_statement()) goto l73;  yyDo(yySet, -2, 0);
  l74:;	
  {  int yypos75= yypos, yythunkpos75= yythunkpos;  if (!yy__()) goto l75;  if (!yymatchChar(';')) goto l75;  if (!yy__()) goto l75;  if (!yy_statement()) goto l75;  yyDo(yySet, -1, 0);  yyDo(yy_1_statements, yybegin, yyend);  goto l74;
  l75:;	  yypos= yypos75; yythunkpos= yythunkpos75;
  }  yyDo(yy_2_statements, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "statements", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l73:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "statements", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_multi_stmnt()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "multi_stmnt"));  if (!yy__()) goto l76;  if (!yymatchChar('{')) goto l76;  if (!yy_sline()) goto l76;  yyDo(yySet, -2, 0);
  l77:;	
  {  int yypos78= yypos, yythunkpos78= yythunkpos;  if (!yy_nll()) goto l78;  if (!yy_sline()) goto l78;  yyDo(yySet, -1, 0);  yyDo(yy_1_multi_stmnt, yybegin, yyend);  goto l77;
  l78:;	  yypos= yypos78; yythunkpos= yythunkpos78;
  }  if (!yy__()) goto l76;  if (!yymatchChar('}')) goto l76;  yyDo(yy_2_multi_stmnt, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "multi_stmnt", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l76:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "multi_stmnt", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_line_stmnt()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "line_stmnt"));  if (!yy__()) goto l79;  if (!yy_statements()) goto l79;  yyDo(yySet, -1, 0);  if (!yy__()) goto l79;  if (!yymatchChar(';')) goto l79;  yyDo(yy_1_line_stmnt, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "line_stmnt", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l79:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "line_stmnt", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_block()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "block"));
  {  int yypos81= yypos, yythunkpos81= yythunkpos;  if (!yy_line_stmnt()) goto l82;  yyDo(yySet, -2, 0);  yyDo(yy_1_block, yybegin, yyend);  goto l81;
  l82:;	  yypos= yypos81; yythunkpos= yythunkpos81;  if (!yy_multi_stmnt()) goto l80;  yyDo(yySet, -1, 0);  yyDo(yy_2_block, yybegin, yyend);
  }
  l81:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "block", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l80:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "block", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_code_lit()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "code_lit"));
  {  int yypos84= yypos, yythunkpos84= yythunkpos;  if (!yy_declaration()) goto l85;  yyDo(yySet, -3, 0);  if (!yy___()) goto l85;  if (!yy_block()) goto l85;  yyDo(yySet, -2, 0);  yyDo(yy_1_code_lit, yybegin, yyend);  goto l84;
  l85:;	  yypos= yypos84; yythunkpos= yythunkpos84;  if (!yy_block()) goto l83;  yyDo(yySet, -1, 0);  yyDo(yy_2_code_lit, yybegin, yyend);
  }
  l84:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "code_lit", yybuf+yypos));  yyDo(yyPop, 3, 0);
  return 1;
  l83:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "code_lit", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_all_literal()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "all_literal"));
  {  int yypos87= yypos, yythunkpos87= yythunkpos;  if (!yy_code_lit()) goto l88;  yyDo(yySet, -2, 0);  yyDo(yy_1_all_literal, yybegin, yyend);  goto l87;
  l88:;	  yypos= yypos87; yythunkpos= yythunkpos87;  if (!yy_literal()) goto l89;  yyDo(yySet, -1, 0);  yyDo(yy_2_all_literal, yybegin, yyend);  goto l87;
  l89:;	  yypos= yypos87; yythunkpos= yythunkpos87;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l86;  if (!yymatchClass((unsigned char *)"\377\373\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l86;
  l90:;	
  {  int yypos91= yypos, yythunkpos91= yythunkpos;  if (!yymatchClass((unsigned char *)"\377\373\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l91;  goto l90;
  l91:;	  yypos= yypos91; yythunkpos= yythunkpos91;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l86;  yyDo(yy_3_all_literal, yybegin, yyend);
  }
  l87:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "all_literal", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l86:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "all_literal", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_def_name()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "def_name"));
  {  int yypos93= yypos, yythunkpos93= yythunkpos;  if (!yy_type_exp()) goto l94;  yyDo(yySet, -3, 0);  if (!yy__()) goto l94;  if (!yy_name()) goto l94;  yyDo(yySet, -2, 0);  yyDo(yy_1_def_name, yybegin, yyend);  goto l93;
  l94:;	  yypos= yypos93; yythunkpos= yythunkpos93;  if (!yy_name()) goto l92;  yyDo(yySet, -1, 0);  yyDo(yy_2_def_name, yybegin, yyend);
  }
  l93:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "def_name", yybuf+yypos));  yyDo(yyPop, 3, 0);
  return 1;
  l92:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "def_name", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_definition()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "definition"));  if (!yy_def_name()) goto l95;  yyDo(yySet, -2, 0);  if (!yy__()) goto l95;  if (!yy_op_assign()) goto l95;  if (!yy_all_literal()) goto l95;  yyDo(yySet, -1, 0);  if (!yy__()) goto l95;  yyDo(yy_1_definition, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "definition", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l95:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "definition", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_type_tuple()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "type_tuple"));  if (!yymatchChar('(')) goto l96;  if (!yy__()) goto l96;  if (!yy_type()) goto l96;  yyDo(yySet, -2, 0);
  l97:;	
  {  int yypos98= yypos, yythunkpos98= yythunkpos;  if (!yy_op_comma()) goto l98;  if (!yy_type()) goto l98;  yyDo(yySet, -1, 0);  yyDo(yy_1_type_tuple, yybegin, yyend);  goto l97;
  l98:;	  yypos= yypos98; yythunkpos= yythunkpos98;
  }  if (!yy__()) goto l96;  if (!yymatchChar(')')) goto l96;  yyDo(yy_2_type_tuple, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "type_tuple", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l96:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "type_tuple", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_type()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "type"));  if (!yy_name()) goto l99;  yyDo(yySet, -1, 0);  yyDo(yy_1_type, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "type", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l99:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "type", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_sum()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "sum"));  if (!yy_product()) goto l100;  yyDo(yySet, -2, 0);
  l101:;	
  {  int yypos102= yypos, yythunkpos102= yythunkpos;
  {  int yypos103= yypos, yythunkpos103= yythunkpos;  if (!yy_op_add()) goto l104;  goto l103;
  l104:;	  yypos= yypos103; yythunkpos= yythunkpos103;  if (!yy_op_sub()) goto l102;
  }
  l103:;	  if (!yy_product()) goto l102;  yyDo(yySet, -1, 0);  yyDo(yy_1_sum, yybegin, yyend);  goto l101;
  l102:;	  yypos= yypos102; yythunkpos= yythunkpos102;
  }  yyDo(yy_2_sum, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "sum", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l100:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "sum", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_op_assign()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "op_assign"));  if (!yymatchChar('=')) goto l105;  if (!yy___()) goto l105;
  yyprintf((stderr, "  ok   %s @ %s\n", "op_assign", yybuf+yypos));
  return 1;
  l105:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "op_assign", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_init()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "init"));  if (!yy_op_assign()) goto l106;  if (!yy_sum()) goto l106;  yyDo(yySet, -1, 0);  yyDo(yy_1_init, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "init", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l106:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "init", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_var()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "var"));  if (!yy_name()) goto l107;  yyDo(yySet, -2, 0);  if (!yy__()) goto l107;
  {  int yypos108= yypos, yythunkpos108= yythunkpos;  if (!yy_init()) goto l108;  yyDo(yySet, -1, 0);  yyDo(yy_1_var, yybegin, yyend);  goto l109;
  l108:;	  yypos= yypos108; yythunkpos= yythunkpos108;
  }
  l109:;	  yyDo(yy_2_var, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "var", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l107:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "var", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_var_list()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "var_list"));  if (!yy_var()) goto l110;  yyDo(yySet, -2, 0);  if (!yy__()) goto l110;
  l111:;	
  {  int yypos112= yypos, yythunkpos112= yythunkpos;  if (!yy_op_comma()) goto l112;  if (!yy_var()) goto l112;  yyDo(yySet, -1, 0);  if (!yy__()) goto l112;
  {  int yypos113= yypos, yythunkpos113= yythunkpos;  if (!yy_name()) goto l113;  goto l112;
  l113:;	  yypos= yypos113; yythunkpos= yythunkpos113;
  }  yyDo(yy_1_var_list, yybegin, yyend);  goto l111;
  l112:;	  yypos= yypos112; yythunkpos= yythunkpos112;
  }  yyDo(yy_2_var_list, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "var_list", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l110:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "var_list", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_type_exp()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "type_exp"));
  {  int yypos115= yypos, yythunkpos115= yythunkpos;  if (!yy_type()) goto l116;  yyDo(yySet, -2, 0);  yyDo(yy_1_type_exp, yybegin, yyend);  goto l115;
  l116:;	  yypos= yypos115; yythunkpos= yythunkpos115;  if (!yy_type_tuple()) goto l114;  yyDo(yySet, -1, 0);  yyDo(yy_2_type_exp, yybegin, yyend);
  }
  l115:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "type_exp", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l114:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "type_exp", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_decl_single()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "decl_single"));  if (!yy_type_exp()) goto l117;  yyDo(yySet, -2, 0);  if (!yy__()) goto l117;  if (!yy_var_list()) goto l117;  yyDo(yySet, -1, 0);  yyDo(yy_1_decl_single, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "decl_single", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l117:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "decl_single", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_op_comma()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "op_comma"));  if (!yymatchChar(',')) goto l118;  if (!yy___()) goto l118;
  yyprintf((stderr, "  ok   %s @ %s\n", "op_comma", yybuf+yypos));
  return 1;
  l118:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "op_comma", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_name()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "name"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l119;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l119;
  l120:;	
  {  int yypos121= yypos, yythunkpos121= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l121;  goto l120;
  l121:;	  yypos= yypos121; yythunkpos= yythunkpos121;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l119;  yyDo(yy_1_name, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "name", yybuf+yypos));
  return 1;
  l119:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "name", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_literal()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 5, 0);
  yyprintf((stderr, "%s\n", "literal"));
  {  int yypos123= yypos, yythunkpos123= yythunkpos;  if (!yy_string_literal()) goto l124;  yyDo(yySet, -5, 0);  yyDo(yy_1_literal, yybegin, yyend);  goto l123;
  l124:;	  yypos= yypos123; yythunkpos= yythunkpos123;  if (!yy_num_literal()) goto l125;  yyDo(yySet, -4, 0);  yyDo(yy_2_literal, yybegin, yyend);  goto l123;
  l125:;	  yypos= yypos123; yythunkpos= yythunkpos123;  if (!yy_declaration()) goto l126;  yyDo(yySet, -3, 0);  if (!yy__()) goto l126;  if (!yy_multi_stmnt()) goto l126;  yyDo(yySet, -2, 0);  yyDo(yy_3_literal, yybegin, yyend);  goto l123;
  l126:;	  yypos= yypos123; yythunkpos= yythunkpos123;  if (!yy_multi_stmnt()) goto l122;  yyDo(yySet, -1, 0);  yyDo(yy_4_literal, yybegin, yyend);
  }
  l123:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "literal", yybuf+yypos));  yyDo(yyPop, 5, 0);
  return 1;
  l122:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "literal", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_const_exp()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "const_exp"));  if (!yy_literal()) goto l127;  yyDo(yySet, -1, 0);  yyDo(yy_1_const_exp, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "const_exp", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l127:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "const_exp", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_op_define()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "op_define"));  if (!yymatchString(":=")) goto l128;  if (!yy___()) goto l128;
  yyprintf((stderr, "  ok   %s @ %s\n", "op_define", yybuf+yypos));
  return 1;
  l128:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "op_define", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_name_list()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "name_list"));  if (!yy_name()) goto l129;  yyDo(yySet, -2, 0);  if (!yy__()) goto l129;
  l130:;	
  {  int yypos131= yypos, yythunkpos131= yythunkpos;  if (!yy_op_comma()) goto l131;  if (!yy_name()) goto l131;  yyDo(yySet, -1, 0);  if (!yy__()) goto l131;  yyDo(yy_1_name_list, yybegin, yyend);  goto l130;
  l131:;	  yypos= yypos131; yythunkpos= yythunkpos131;
  }  yyDo(yy_2_name_list, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "name_list", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l129:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "name_list", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_auto_decl()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "auto_decl"));  if (!yy_name_list()) goto l132;  if (!yy__()) goto l132;  if (!yy_op_define()) goto l132;  if (!yy_const_exp()) goto l132;  yyDo(yy_1_auto_decl, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "auto_decl", yybuf+yypos));
  return 1;
  l132:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "auto_decl", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_declaration()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "declaration"));  if (!yy_decl_single()) goto l133;  yyDo(yySet, -2, 0);  if (!yy__()) goto l133;
  l134:;	
  {  int yypos135= yypos, yythunkpos135= yythunkpos;  if (!yymatchChar(',')) goto l135;  if (!yy__()) goto l135;  if (!yy_decl_single()) goto l135;  yyDo(yySet, -1, 0);  if (!yy__()) goto l135;  yyDo(yy_1_declaration, yybegin, yyend);  goto l134;
  l135:;	  yypos= yypos135; yythunkpos= yythunkpos135;
  }  yyDo(yy_2_declaration, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "declaration", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l133:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "declaration", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy___()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "__"));  if (!yy__()) goto l136;
  {  int yypos137= yypos, yythunkpos137= yythunkpos;  if (!yy_nl()) goto l137;  if (!yy__()) goto l137;  goto l138;
  l137:;	  yypos= yypos137; yythunkpos= yythunkpos137;
  }
  l138:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "__", yybuf+yypos));
  return 1;
  l136:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "__", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_define()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "define"));  if (!yymatchString("def")) goto l139;  if (!yy___()) goto l139;  if (!yy_definition()) goto l139;  yyDo(yySet, -1, 0);  yyDo(yy_1_define, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "define", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l139:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "define", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_declare()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "declare"));
  {  int yypos141= yypos, yythunkpos141= yythunkpos;  if (!yymatchString("var")) goto l142;  if (!yy___()) goto l142;  if (!yy_declaration()) goto l142;  yyDo(yySet, -1, 0);  yyDo(yy_1_declare, yybegin, yyend);  goto l141;
  l142:;	  yypos= yypos141; yythunkpos= yythunkpos141;  if (!yy_auto_decl()) goto l140;  yyDo(yy_2_declare, yybegin, yyend);
  }
  l141:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "declare", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l140:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "declare", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_nll()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "nll"));  if (!yy__()) goto l143;  if (!yy_nl()) goto l143;  if (!yy__()) goto l143;
  yyprintf((stderr, "  ok   %s @ %s\n", "nll", yybuf+yypos));
  return 1;
  l143:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "nll", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_decl()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "decl"));
  {  int yypos145= yypos, yythunkpos145= yythunkpos;  if (!yy_declare()) goto l146;  yyDo(yySet, -2, 0);  yyDo(yy_1_decl, yybegin, yyend);  goto l145;
  l146:;	  yypos= yypos145; yythunkpos= yythunkpos145;  if (!yy_define()) goto l147;  yyDo(yySet, -1, 0);  yyDo(yy_2_decl, yybegin, yyend);  goto l145;
  l147:;	  yypos= yypos145; yythunkpos= yythunkpos145;  if (!yy__()) goto l148;  if (!yymatchString("//")) goto l148;
  l149:;	
  {  int yypos150= yypos, yythunkpos150= yythunkpos;  if (!yymatchClass((unsigned char *)"\377\373\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l150;  goto l149;
  l150:;	  yypos= yypos150; yythunkpos= yythunkpos150;
  }  yyDo(yy_3_decl, yybegin, yyend);  goto l145;
  l148:;	  yypos= yypos145; yythunkpos= yythunkpos145;  if (!yy__()) goto l151;  yyDo(yy_4_decl, yybegin, yyend);  goto l145;
  l151:;	  yypos= yypos145; yythunkpos= yythunkpos145;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l144;  if (!yymatchClass((unsigned char *)"\377\371\377\377\376\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l144;
  l154:;	
  {  int yypos155= yypos, yythunkpos155= yythunkpos;  if (!yymatchClass((unsigned char *)"\377\371\377\377\376\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l155;  goto l154;
  l155:;	  yypos= yypos155; yythunkpos= yythunkpos155;
  }  if (!yy__()) goto l144;
  l152:;	
  {  int yypos153= yypos, yythunkpos153= yythunkpos;  if (!yymatchClass((unsigned char *)"\377\371\377\377\376\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l153;
  l156:;	
  {  int yypos157= yypos, yythunkpos157= yythunkpos;  if (!yymatchClass((unsigned char *)"\377\371\377\377\376\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l157;  goto l156;
  l157:;	  yypos= yypos157; yythunkpos= yythunkpos157;
  }  if (!yy__()) goto l153;  goto l152;
  l153:;	  yypos= yypos153; yythunkpos= yythunkpos153;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l144;  yyDo(yy_5_decl, yybegin, yyend);
  }
  l145:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "decl", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l144:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "decl", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_EOF()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "EOF"));
  {  int yypos159= yypos, yythunkpos159= yythunkpos;  if (!yymatchDot()) goto l159;  goto l158;
  l159:;	  yypos= yypos159; yythunkpos= yythunkpos159;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "EOF", yybuf+yypos));
  return 1;
  l158:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EOF", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy__()
{
  yyprintf((stderr, "%s\n", "_"));
  l161:;	
  {  int yypos162= yypos, yythunkpos162= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l162;  goto l161;
  l162:;	  yypos= yypos162; yythunkpos= yythunkpos162;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "_", yybuf+yypos));
  return 1;
}
YY_RULE(int) yy_decls()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "decls"));  if (!yy_decl()) goto l163;  yyDo(yySet, -2, 0);
  l164:;	
  {  int yypos165= yypos, yythunkpos165= yythunkpos;  if (!yy_nll()) goto l165;  if (!yy_decl()) goto l165;  yyDo(yySet, -1, 0);  yyDo(yy_1_decls, yybegin, yyend);  goto l164;
  l165:;	  yypos= yypos165; yythunkpos= yythunkpos165;
  }  yyDo(yy_2_decls, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "decls", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l163:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "decls", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_program()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "program"));  if (!yy_decls()) goto l166;  if (!yy__()) goto l166;  if (!yy_EOF()) goto l166;  yyDo(yy_1_program, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "program", yybuf+yypos));
  return 1;
  l166:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "program", yybuf+yypos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)();

YY_PARSE(int) YYPARSEFROM(yyrule yystart)
{
  int yyok;
  if (!yybuflen)
    {
      yybuflen= 1024;
      yybuf= (char*)malloc(sizeof(char)* yybuflen);
      yytextlen= 1024;
      yytext= (char*)malloc(sizeof(char)* yytextlen);
      yythunkslen= 32;
      yythunks= (yythunk*)malloc(sizeof(yythunk)* yythunkslen);
      yyvalslen= 70;
      yyvals= __MALLOC(YYSTYPE, yyvalslen);
      yybegin= yyend= yypos= yylimit= yythunkpos= 0;
    }
  yybegin= yyend= yypos;
  yythunkpos= 0;
  yyval= yyvals;
  yyok= yystart();
  if (yyok) yyDone();
  yyCommit();
  return yyok;
  (void)yyrefill;
  (void)yymatchDot;
  (void)yymatchChar;
  (void)yymatchString;
  (void)yymatchClass;
  (void)yyDo;
  (void)yyText;
  (void)yyDone;
  (void)yyCommit;
  (void)yyAccept;
  (void)yyPush;
  (void)yyPop;
  (void)yySet;
  (void)yytextmax;
}

YY_PARSE(int) YYPARSE(void)
{
  return YYPARSEFROM(yy_program);
}

#endif


main ()
	{
	if (! yyparse())
		printf("error on line %d\n", source_line);
	else
		printf("parsed %d lines\n", source_line);
	}

#include <stdio.h>
     
void yyerror (char const * s)  /* Called by yyparse on error */
	{
//	yydebug = 1;
	printf ("%s\n", s);
	}


